### ISSUE TITLE
Disaster recovery

### ISSUE THREAD

**Issue by deadtrickster** [rabbitmq/ra#93] opened 2019-05-31 07:50 UTC
Sorry if I missed this in the docs...

How to perform disaster recovery with default log module?:
 - What and when to backup;
 - How to do cold restart having that backup?

Thanks

**Comment by michaelklishin** [comment] 2019-05-31 09:27
We plan to introduce a "passive follower" role that can accumulate and truncate the log but not apply any effects. In many cases starting a node with an existing log directory and set of peers would be enough but it's something we haven't investigated in details.

**Comment by michaelklishin** [comment] 2019-05-31 09:28
I believe this is effectively a duplicate of #44.

**Closed by michaelklishin** 2019-05-31 09:28 UTC
